In [1]:
import pandas as pd
import numpy as np

In [13]:
data=pd.read_csv("book1.csv",encoding="latin-1",index_col=False)
data.head(5)

,Unnamed: 0,User.ID,Book.Title,Book.Rating
0,1,276726,Classical Mythology,5
1,2,276729,Clara Callan,3
2,3,276729,Decision in Normandy,6
3,4,276736,Flu: The Story of the Great Influenza Pandemic...,8
4,5,276737,The Mummies of Urumchi,6

In [ ]:
data.rename({"Unnamed: 0":"S_no"},axis=1,inplace=True)

In [24]:
len(data["User.ID"])

10000

In [67]:
len(data["Book.Title"].unique())

9659

In [21]:
len(data["User.ID"].unique())

2182

In [32]:
unique_id=data["User.ID"].unique()
unique_id_df=pd.DataFrame(unique_id,columns=["unique_id"])
unique_id_df

      unique_id
0        276726
1        276729
2        276736
3        276737
4        276744
...         ...
2177     162107
2178     162109
2179     162113
2180     162121
2181     162129

[2182 rows x 1 columns]

In [38]:
data["unique_id"]=unique_id_df
data

,S_no,User.ID,Book.Title,Book.Rating,unique_id
0,1,276726,Classical Mythology,5,276726.0
1,2,276729,Clara Callan,3,276729.0
2,3,276729,Decision in Normandy,6,276736.0
3,4,276736,Flu: The Story of the Great Influenza Pandemic...,8,276737.0
4,5,276737,The Mummies of Urumchi,6,276744.0
...,...,...,...,...,...
9995,9996,162121,American Fried: Adventures of a Happy Eater.,7,NaN
9996,9997,162121,Cannibal In Manhattan,9,NaN
9997,9998,162121,How to Flirt: A Practical Guide,7,NaN
9998,9999,162121,Twilight,8,NaN
9999,10000,162129,Kids Say the Darndest Things,6,NaN

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   S_no         10000 non-null  int64
 1   User.ID      10000 non-null  int64
 2   Book.Title   10000 non-null  object
 3   Book.Rating  10000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 312.6+ KB

In [89]:
user_book_df = data.pivot_table(columns='User.ID',
                                 index='Book.Title',
                                 values='Book.Rating')

In [90]:
user_book_df

User.ID,8,9,10,12,14,16,17,19,22,26,...,278831,278832,278836,278843,278844,278846,278849,278851,278852,278854
Book.Title,,,,,,,,,,,,,,,,,,,,,
"Jason, Madison &amp",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Other Stories;Merril;1985;McClelland &amp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Repairing PC Drives &amp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\Well, there's your problem\: Cartoons",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
iI Paradiso Degli Orchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN
stardust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ãƒ?Ã‚?bermorgen.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
user_book_df.fillna(0,inplace=True)
user_book_df

User.ID,8,9,10,12,14,16,17,19,22,26,...,278831,278832,278836,278843,278844,278846,278849,278851,278852,278854
Book.Title,,,,,,,,,,,,,,,,,,,,,
"Jason, Madison &amp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Other Stories;Merril;1985;McClelland &amp,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Repairing PC Drives &amp,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\Well, there's your problem\: Cartoons",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
iI Paradiso Degli Orchi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
stardust,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ãƒ?Ã‚?bermorgen.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [94]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [96]:
user_sim = 1 - pairwise_distances( user_book_df.values,metric='cosine')
user_sim

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [98]:
book_titles = user_book_df.index

Index([' Jason, Madison &amp', ' Other Stories;Merril;1985;McClelland &amp',
       ' Repairing PC Drives &amp', ''48',
       ''O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities',
       '...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR',
       '01-01-00: A Novel of the Millennium',
       '1,401 More Things That P*Ss Me Off', '10 Commandments Of Dating',
       '100 Great Fantasy Short, Short Stories',
       ...
       'Zora Hurston and the Chinaberry Tree (Reading Rainbow Book)',
       '\Even Monkeys Fall from Trees\ and Other Japanese Proverbs',
       '\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment',
       '\More More More,\ Said the Baby', '\O\ Is for Outlaw',
       '\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character',
       '\Well, there's your problem\: Cartoons', 'iI Paradiso Degli Orchi',
       'stardust', 'Ãƒ?Ã‚?bermorgen.'],
      dtype='object', name='Book.Title', length=9659)

In [104]:
data.rename({"Book.Title":"Book_Title"},axis=1,inplace=True)

In [99]:
# Define function provide top recommendations
def recommender(book_names):  
    # Initialize recommendations output length of number of books
    recommendations = np.zeros(user_sim.shape[0])
    # Loop through the books titles that the user has rated
    for book in book_names:
        # Sum the correlations
        recommendations = recommendations + user_sim[list(book_titles).index(book)]
    # Convert recommendations into dataframe
    recommendations_df = pd.DataFrame({
            'Title': book_titles,
            'Recommendation': recommendations})
    # Remove book titles that the user has already rated
    recommendations_df = recommendations_df[~(recommendations_df.Title.isin(book_names))]
    # Sort from most correlated to least correlated
    recommendations_df = recommendations_df.sort_values(by=['Recommendation'], ascending = False)
    return recommendations_df

In [105]:
# Define user
user = 8

# Get list of books user has rated
user_books = data[data["User.ID"] == user].Book_Title.tolist()  
print('books rated by user\n')
print(user_books)
# Get list of recommendations
recommendations = recommender(user_books)

# Print out top 10 recommendations
print('\nRecommendations for user\n')
print(recommendations.Title.head(10))

books rated by user

['Ancient Celtic Romances', 'The Western way: A practical guide to the Western mystery tradition', 'Wings', 'Truckers', 'Keepers of the Earth Teachers Guide', 'The Celts Activity Book', 'The Art Of Celtia']

Recommendations for user

0                                     Jason, Madison &amp
6431    Spiritual Cleansing: A Handbook of Psychic Pro...
6433                Splintered Moon (Velvet Glove, No 19)
6434    Sportin' a 'Tude: What Your Attitude Says When...
6435       Spot Visits His Grandparents (Picture Puffins)
6436                                         Spring Break
6437    Spring Break (Sweet Valley High Super Edition,...
6438                                    Spring Collection
6439                                         Spring Fancy
6440                                        Spring Fever!
Name: Title, dtype: object